org: jackshort
app: ivx-services
service: ivx-services
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        STATUS_TABLE: ivx-status
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
          Resource: '*'

functions:
    generateMetadata:
        handler: handler.generateMetadata
        events:
            - httpApi:
                  path: /generateMetadata
                  method: post

    generateImage:
        handler: handler.generateImage
        events:
            - s3:
                  bucket: token.iv-x.xyz
                  event: s3:ObjectCreated:*
                  existing: true

    generateFrontScreen:
        handler: handler.generateFrontScreen
        events:
            - s3:
                  bucket: media.iv-x.xyz
                  event: s3:ObjectCreated:*
                  existing: true

    redeemToken:
        handler: handler.redeemToken
        events:
            - httpApi:
                  path: /redeemToken
                  method: post

plugins:
    - serverless-plugin-typescript
    - serverless-offline
